src/chat/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'chat'
urlpatterns = [
    url(r'^(?P<pk>[0-9]+)$', views.ChatView.as_view(), name='chats_num'),
    url(r'^$', views.ChatView.as_view(), name='chats'),
    url(r'^$', views.update_messages, name='post_message'),
    url(r'^get_messages/(?P<pk>[0-9]+)$', views.get_messages, name='get_messages')
]

src/event/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'event'
urlpatterns = [
    url(r'last/$', views.EventsView.as_view(), name='events'),
]

src/login/urls.py
from django.conf.urls import url

from . import views

app_name = 'login'
urlpatterns = [
	url(r'^login(?P<next>.+)', views.login, name='login'),
 	url(r'^logout(?P<next>.+)', views.logout, name='logout'),
 	url(r'^register/(?P<next>.+)', views.register, name='register'),
]

src/social_n/urls.py
from rest_framework import routers
import user_profile.views
import comment.views
import chat.views
import message.views
from django.conf import settings
from rest_framework.authtoken import views as restviews

from . import views

from django.conf.urls import url, include
from django.contrib import admin

import oauth2_provider.views as oauth2_views


router = routers.DefaultRouter()
router.register(r'users', user_profile.views.UserViewSet)
router.register(r'comments', comment.views.CommentViewSet)
router.register(r'chat', chat.views.ChatViewSet)
router.register(r'message', message.views.MessageViewSet)

# OAuth2 provider endpoints
oauth2_endpoint_views = [
    url(r'^authorize/$', oauth2_views.AuthorizationView.as_view(), name="authorize"),
    url(r'^token/$', oauth2_views.TokenView.as_view(), name="token"),
    url(r'^revoke-token/$', oauth2_views.RevokeTokenView.as_view(), name="revoke-token"),
]


if settings.DEBUG:
    # OAuth2 Application Management endpoints
    oauth2_endpoint_views += [
        url(r'^applications/$', oauth2_views.ApplicationList.as_view(), name="list"),
        url(r'^applications/register/$', oauth2_views.ApplicationRegistration.as_view(), name="register"),
        url(r'^applications/(?P<pk>\d+)/$', oauth2_views.ApplicationDetail.as_view(), name="detail"),
        url(r'^applications/(?P<pk>\d+)/delete/$', oauth2_views.ApplicationDelete.as_view(), name="delete"),
        url(r'^applications/(?P<pk>\d+)/update/$', oauth2_views.ApplicationUpdate.as_view(), name="update"),
    ]

    # OAuth2 Token Management endpoints
    oauth2_endpoint_views += [
        url(r'^authorized-tokens/$', oauth2_views.AuthorizedTokensListView.as_view(), name="authorized-token-list"),
        url(r'^authorized-tokens/(?P<pk>\d+)/delete/$', oauth2_views.AuthorizedTokenDeleteView.as_view(),
            name="authorized-token-delete"),
    ]

urlpatterns = router.urls + [
    url(r'^admin/', admin.site.urls),
    url(r'^api/hello', views.ApiEndpoint.as_view()),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^social/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    url(r'^login/', include('login.urls')),
    url(r'^secret$', views.secret_page, name='secret'),
    url(r'^socialn/', include('chat.urls')),
    url(r'^events/', include('event.urls')),
    url(r'^api-token-auth/', restviews.obtain_auth_token),
]

src/base/models.py
# coding: utf-8
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone
import datetime


class PublicationModel(models.Model):
    class Meta:
        abstract = True

    pub_date = models.DateTimeField(verbose_name='creation_date', default=timezone.now)
    mod_date = models.DateTimeField(verbose_name='modification_date', default=timezone.now)


class EmailSenderModel(models.Model):
    class Meta:
        abstract = True

    def send_email(self):
        pass


class ModelWithLikes(models.Model):

    class Meta:
        abstract = True

    likes_count = models.IntegerField(default=0, verbose_name="likes_count")


class TextModel(models.Model):

    class Meta:
        abstract = True

    text = models.TextField(verbose_name='message_text')
    author = models.ForeignKey(User, null=True, blank=True, verbose_name='message_author')

    published = models.BooleanField(default=True)

    def __str__(self):
        return self.text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def message_beginning(self):
        return self.text[:50]

src/login/models.py
from django.db import models
from django.contrib.auth.models import User, UserManager, AbstractBaseUser
import os
from django.utils import timezone
from chat.models import Chat, Membership
from message.models import Message
from rest_framework import serializers


def get_image_path(instance, filename):
    return os.path.join('users', str(instance.user.id), 'ava.jpg')


class UserProfile(models.Model):

    user = models.OneToOneField(User)
    #avatar = models.ImageField(upload_to=get_image_path, blank=True, null=True)
    last_activity = models.DateTimeField(default=timezone.now)

    def __unicode__(self):
        return self.user.username

    def get_unread_messages(self):
        chats = Chat.objects.filter(chat_to_user__user=self.user)

        if len(chats) == 0:
            return ''

        message = "You got messages in {} chats, while you were offline:\n".format(len(chats))

        for chat in chats:
            lost_messages = Message.objects.filter(chat=chat, pub_date__gte=self.last_activity).order_by('pub_date')
            for lost_message in lost_messages:
                message += "In chat " + chat.name + " :\n" + "    " + lost_message.author.username + ": " + lost_message.text + '\n'

        return message


class UserProfileSerializer(serializers.ModelSerializer):

    class Meta:
        model = UserProfile
        fields = ('pk', 'user', 'last_activity')

src/login/forms.py
# coding: utf-8

from .models import UserProfile
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')
        verbose_name = u'Пользователь'
        verbose_name_plural = u'Пользователи'
        ordering = ('-date_joined', )


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ()
        verbose_name = u'Профиль'
        verbose_name_plural = u'Профили'
        ordering = ('-user.date_joined', )

src/login/views.py
from django.shortcuts import redirect, render
from django.contrib import auth
from .forms import UserForm, UserProfileForm
from django.template import RequestContext
import sys


def login(request, next):

    authenticated = False
    redirect_to = next
    login_error = None

    if request.method == 'POST':

        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            authenticated = True
        else:
            login_error = "User not found"

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    if authenticated:
        auth.login(request, user)
        return redirect(redirect_to)
    else:
        return render(request, 'login/login.html', {'login_error': login_error, 'user_form': UserForm(), \
                                                 'user_profile_form': UserProfileForm(), 'redirect_to' : redirect_to})


def logout(request, next):
    auth.logout(request)
    redirect_to = next
    return redirect(redirect_to)  


def register(request, next):
    context = RequestContext(request)
    registered = False

    if request.method == 'POST':
       
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()

            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            sys.stdout.flush()

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    redirect_to = next

    if not registered:
        return render(request, 'login/register.html', {'user_form': user_form, 'user_profile_form': profile_form, 'redirect_to' : redirect_to})
    else:
        return redirect(redirect_to)
    

src/social_n/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from oauth2_provider.views.generic import ProtectedResourceView
from django.http.response import HttpResponse


def login(request):
    return render(request, 'social_n/login.html')


@login_required()
def secret_page(request, *args, **kwargs):
    return HttpResponse('Secret contents!', status=200)


class ApiEndpoint(ProtectedResourceView):
    def get(self, request, *args, **kwargs):
        return HttpResponse('Hello, OAuth2!')

src/templates/social_n/base.html
<!DOCTYPE html>


<html lang="en">
<head>
    <meta charset="UTF-8">
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="https://unpkg.com/react@15.3.2/dist/react.js"></script>
    <script src="https://unpkg.com/react-dom@15.3.2/dist/react-dom.js"></script>
    <script src="https://unpcg.com/babel-standalone@6.5.0/babel.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/i18n/jquery-ui-i18n.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.4.2/chosen.min.css">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.4.2/chosen.jquery.min.js"></script>

    {% load staticfiles %}
    <script src="{% static 'js/cookie.js' %}"></script>

    {% load staticfiles %}
    <script type="text/babel" src="{% static "js/message_jsx/app.jsx" %}"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1"/>

    {% load staticfiles %}
    <link href="{% static "css/bootstrap/css/bootstrap.css" %}" rel="stylesheet">

    {% load staticfiles %}
    <link href="{% static "css/style.css" %}" rel="stylesheet">

    {% block js %}
    {% endblock %}

</head>
<body role="document">

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">

        <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'chat:chats' %}"></a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
             <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'chat:chats' %}">Home</a></li>
                <li><a href="{% url 'chat:chats' %}">Messages</a></li>
                 <li><a href="{% url 'event:events' %}">News</a></li>
             </ul>

            <form class="navbar-form navbar-right">
              {% if  user.is_authenticated %}
                    <a href="#" class="btn btn-link" role="button">{{ user.username }}</a>
                    <a href="{% url 'login:logout' request.get_full_path|urlencode %}" type="submit" class="btn btn-default">Sign out</a>
              {% else %}
                  <a href="{% url 'login:login' request.get_full_path|urlencode %}" role = "button" class="btn btn-default">Sign in</a>
                  <a href="{% url 'login:register' request.get_full_path|urlencode %}"  role="button" class="btn btn-default">Register</a>
              {% endif %}
             </form>

        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-md-8">
                {% block title %}
                {% endblock %}

                {% block content %}
                {% endblock %}
            </div>

            <div class="col-md-3 col-md-offset-1 blog-sidebar">
                {%  block fast-navig %}
                    <div class="sidebar-module">
                        <div class="btn-group btn-group-justified">

                        </div>
                    </div>
                {%  endblock %}

                {% block sidecont %}

                {% endblock %}
            </div>
        </div>

    </div>

    {% block footer %}
        <!-- Footer-->
        <div id="footer">
          <div class="container">
            <p class="text-muted">Stackoverflow 2016-2016
              <address class="text-muted">
                <strong>Gainsteva Tatiana: </strong>
                <a href="mailto:#">killmeplease</a>
              </address>
            </p>
          </div>
        </div>
    {% endblock %}


</body>
</html>

src/templates/social_n/login.html
<div><a href="{% url "social:begin" "vk-oauth2" %}">Войти через вк</a></div>
{{user}}

<input type="hidden" name="next" value="{{ next }}" />